general:
  dataset_root: "datasets/MSLR-WEB10K"
  partition: "test"
  folds: ["Fold1"]
  seed: 0
  mode: "list"
  run_eval_mode: True
  list_length: 20
  k: 10
  relevance_threshold: 3 # doc is relevant if relevance >= this threshold
  debug: False
  debug_freq: 100 # print debug statements every N steps

training:
    epochs: 50
    batch_size: 100
    shuffle: True
    num_workers: 8
    use_cuda: True
    optimizer:
        step_rule: "AdamW"
        learning_rate: 0.0001
        weight_decay: 0.00001
        use_grad_clip: False
        clip_grad_norm: 1.0

logging:
    save_checkpoint: True # save a checkpoint every epoch
    experiment_tag: 'direct_ranker_lists_test'
    load_checkpoint: True # use a saved checkpoint
    resume_training: False # if false, discard everything except model weights
    load_from_tag: 'direct_ranker_lists_train' # if you want to load from prev experiment

rank_model:
  xavier_init: False
  input_dim: 136
  mlp_n_layers: 3
  mlp_hidden_dim: 128
  mlp_p_dropout: 0.1
  leaky_slope: 0.01

# ~ 0.8 ndcg@10
# ~ 0.8 map@10