general:
  dataset_root: "datasets/MSLR-WEB10K"
  partition: "train"
  folds: ["Fold1"]
  seed: 0
  mode: "pair"
  run_eval_mode: False
  k: 10

training:
    epochs: 40
    batch_size: 100
    shuffle: True
    num_workers: 8
    use_cuda: True
    optimizer:
        step_rule: "AdamW"
        learning_rate: 0.0001
        weight_decay: 0.00001
        use_grad_clip: False
        clip_grad_norm: 1.0

logging:
    save_checkpoint: True # save a checkpoint every epoch
    experiment_tag: 'direct_ranker_pairs'
    load_checkpoint: False # use a saved checkpoint
    resume_training: True # if false, discard everything except model weights
    load_from_tag: 'your_previous_experiment_model' # if you want to load from prev experiment

rank_model:
  xavier_init: False
  input_dim: 136
  mlp_n_layers: 3
  mlp_hidden_dim: 128
  mlp_p_dropout: 0.0
  leaky_slope: 0.01
